

"""
Module to modify policers on a Zhone MXK819/319, based on input file
generated by mxk_policer_report.py
"""

import csv
import time
import getpass
from netmiko import ConnectHandler

"""
Gather connection information
"""
host = raw_input('Enter hostname of OLT: ')
username = raw_input ('Enter username for OLT: ')
password = getpass.getpass('Enter password for OLT: ')
rate_to_change = raw_input('Enter Mbps rate of the services to change e.g. 25, 50 or 100: ')
ingress_rule = raw_input('Enter the new ingress rule group number: ')
egress_rule = raw_input('Enter the new egress rule group number: ')
input_file = raw_input('Enter the full name of the input file: ')
platform = 'cisco_ios'
print ('Connecting....')
# no handler type for zhone but 'cisco-ios' seems to work



"""
Connect to device using Netmiko
"""
device = ConnectHandler(device_type=platform, ip=host, username=username, password=password)
print ('Connected to OLT, gathering info.....')

"""
Read input file and loop over entries to locate ports with the rate that
you want to change. If port matches that rate modify the port to the new
ingress and egress rule.
"""
with open(input_file) as f:
    reader = csv.reader(f)

    inputs = {}
    for row in reader:
        if row[1] == rate_to_change:
            print ('Modifying port {}'.format(row[0]))
            device.send_command('bridge modify {} ipktrule {}'.format(row[0], ingress_rule))
            time.sleep(1)
            device.send_command('bridge modify {} epktrule {}'.format(row[0], egress_rule))
            time.sleep(1)

print ('Changes complete')
device.disconnect()
print ('Disconnected from OLT')
print ('Finished')


